sudo: required
language: node_js
dist: trusty
node_js:
  - "10"
branches:
  only:
    - develop
    - master
before_script:
  - npm install -g @compodoc/compodoc
  - npm install -g @angular/cli
script:
  - npm run testfront
  - npm run testback
  - npm run build
  - npm run gendocs