sudo: required
language: node_js
dist: trusty
node_js:
  - "10"
branches:
  only:
    - develop
    - master
before_script:
  - npm install -g @angular/cli
  - npm install
script:
  - npm run testfront
  - npm run testback
  - npm run build