sudo: required
language: node_js
dist: trusty
node_js:
  - "10"
branches:
  only:
    - develop
    - master
before_script:
  - npm install -g @angular/cli
  - npm install
script:
  - npm test testfront
  - npm test testback
  - npm run build